### ISSUE TITLE
Port simplify.js perf improvements

### ISSUE THREAD

**Issue by mourner** [mattdesl/simplify-path#1]
Douglas-Peucker implementation got significantly faster with a recursive implementation: https://github.com/mourner/simplify-js/blob/0b0e5d870faaf0b55e48af310444ef9ccf169d3a/simplify.js#L71-L100

**Comment by mattdesl** [comment]
Thanks @mourner, is the optimization only worthwhile on engines that support tail call optimization?

**Comment by mattdesl** [comment]
will merge shortly
https://github.com/mattdesl/simplify-path/tree/feature/recursive

**Comment by mourner** [comment]
@mattdesl probably not, since the gain most likely comes from building the `simplified` array directly without first creating a `markers` array.

**Comment by mattdesl** [comment]
ok cool :+1: 

Thanks for letting me know.

**Comment by mourner** [comment]
Thanks!
