### ISSUE TITLE
What is the unit of tolerance?

### ISSUE THREAD

**Issue by mickeyjohn** [mattdesl/simplify-path#2]
Thanks for the great efforts making this library. Could any one help explain how to use the tolerance? what is the unit ?

**Comment by mattdesl** [comment]
The tolerance is relative to the units you are passing in. So, for example, if you are passing in a path in screen pixels, you can imagine the tolerance would be relative to screen pixels. If you are passing in a path where the units are in meters, you can then imagine the tolerance would be specified in meters.

**Comment by mickeyjohn** [comment]
Thank you very much @mattdesl for your clear explanation.
